# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      deployments: write
    steps:

    # - uses: actions/delete-package-versions@v5
    #   with:
    #     package-version-ids: '1.0'
    #     package-name: 'org.bughouse.fen.bughouse-fen-validator'
    #     package-type: 'maven'
    #     # min-versions-to-keep: 1.0
    
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -X --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
